repo_url: https://github.com/flanksource/konfigadm/
repo_name: Konfigadm
site_name: Konfigadm
theme: material
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - codehilite:
      linenums: true
nav:
  - Installation: ./installation.md
  - Concepts: ./concepts.md
  - Tags: ./tags.md
  - Integration: ./integration.md
  - Apps:
      - Containers: ./containers.md
      - CRI: ./cri.md
      - Kubernetes: ./k8s.md
  - Native:
      - Packages: ./packages.md
      - Files: ./files.md
      - Templates: ./templates.md
      - Sysctl: ./sysctl.md
      - Environment: ./environment.md
      - Trusted CA: ./trusted_ca.md
  - Primitives:
      - Commands: ./commands.md
      - Files: ./native_files.md
