version: 2
go: &go
  environment:
    GO111MODULE: "on"
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/moshloop/konfigadm
test: &test
  <<: *go
  steps:
    - setup_remote_docker
    - checkout
    - run: go mod download
    - run: IMAGE="jrei/systemd-$CIRCLE_JOB" make test integration
    - store_test_results:
        path: test-output
jobs:
  "ubuntu:16.04":
      <<: *test
  "ubuntu:18.04":
      <<: *test
  "debian:9":
      <<: *test
  "centos:7":
      <<: *test
  "fedora:latest":
      <<: *test
  release:
      <<: *go
      steps:
        - checkout
        - setup_remote_docker
        - run: go mod download
        - run: ./scripts/release.sh
  docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install mkdocs mkdocs-material pymdown-extensions Pygments
      - run: make docs
workflows:
  version: 2
  build:
    jobs:
      - "ubuntu:16.04"
      - "ubuntu:18.04"
      - "debian:9"
      - "centos:7"
      - "fedora:latest"
      - release:
          context: Github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - docs:
          context: Github

