version: 2
go: &go
  environment:
    GO111MODULE: "on"
  docker:
    - image: circleci/golang:1.13
  working_directory: /go/src/github.com/moshloop/konfigadm

test: &test
  <<: *go
  steps:
    - setup_remote_docker:
        version: 18.09.3
    - checkout
    - run: go mod download
    - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
    - run: golangci-lint run ./... --enable golint
    - run: make test linux "$CIRCLE_JOB"
    - store_test_results:
        path: test-output
jobs:
  "ubuntu16":
    <<: *test
  "ubuntu18":
    <<: *test
  "ubuntu20":
    <<: *test
  "debian10":
    <<: *test
  "centos7":
    <<: *test
  "fedora29":
    <<: *test
  "amazonlinux2":
    <<: *test
workflows:
  version: 2
  build:
    jobs:
      - "ubuntu16"
      - "ubuntu18"
      - "ubuntu20"
      - "debian10"
      - "centos7"
      - "amazonlinux2"
      # - "fedora29"
